routes/dashboard.php
<?php

use App\Http\Controllers\Dashboard\CategoryController;
use App\Http\Controllers\Dashboard\Content\ContentController;
use App\Http\Controllers\Dashboard\CurriculumController;
use App\Http\Controllers\Dashboard\Cv\CurriculumAcademicComplementaryController;
use App\Http\Controllers\Dashboard\Cv\CurriculumAcademicComplementaryOnlineController;
use App\Http\Controllers\Dashboard\Cv\CurriculumAcademicTrainingController;
use App\Http\Controllers\Dashboard\Cv\CurriculumAvailableRepositoryTypeController;
use App\Http\Controllers\Dashboard\Cv\CurriculumCollaborationController;
use App\Http\Controllers\Dashboard\Cv\CurriculumExperienceAccreditedController;
use App\Http\Controllers\Dashboard\Cv\CurriculumExperienceAdditionalController;
use App\Http\Controllers\Dashboard\Cv\CurriculumExperienceNoAccreditedController;
use App\Http\Controllers\Dashboard\Cv\CurriculumExperienceOtherController;
use App\Http\Controllers\Dashboard\Cv\CurriculumExperienceSelfEmployedController;
use App\Http\Controllers\Dashboard\Cv\CurriculumHobbyController;
use App\Http\Controllers\Dashboard\Cv\CurriculumJobController;
use App\Http\Controllers\Dashboard\Cv\CurriculumProjectController;
use App\Http\Controllers\Dashboard\Cv\CurriculumRepositoryController;
use App\Http\Controllers\Dashboard\Cv\CurriculumServiceController;
use App\Http\Controllers\Dashboard\Cv\CurriculumSkillController;
use App\Http\Controllers\Dashboard\Hardware\HardwareDeviceController;
use App\Http\Controllers\Dashboard\Hardware\HardwareEnergyController;
use App\Http\Controllers\Dashboard\LanguageController;
use App\Http\Controllers\Dashboard\PlatformController;
use App\Http\Controllers\Dashboard\TagController;
use App\Http\Controllers\Dashboard\Users\UserController;
use App\Http\Controllers\Dashboard\EmailController;
use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\Dashboard\Content\ContentPageController;
use \App\Http\Controllers\Dashboard\AdminLteController;
use \App\Http\Controllers\Dashboard\TechnologyController;


############################################################
##                      Dashboard                         ##
############################################################
Route::group(['prefix' => '/', 'middleware' => ['auth', 'verified']], function () {
    Route::get('/', function () {
        return view('dashboard.index');
    })->name('dashboard.index');


    ## Listado con todos los tipos de archivos que hay en la plataforma.
    Route::get('/app/file-types', [AdminLteController::class, 'fileTypesIndex'])
        ->name('dashboard.app.file_types.index');

    Route::post('/app/file-types/update/icon/{fileType}', [AdminLteController::class, 'fileTypesIconUpdate'])
        ->name('dashboard.app.file_types.update.icon');
});

############################################################
##                      Emails                            ##
############################################################
Route::group(['prefix' => '/emails', 'middleware' => ['auth', 'verified']],
    function () {

        Route::get('/index', [EmailController::class, 'index'])
            ->name('dashboard.email.index');


        Route::group(['prefix' => '/ajax'], function () {
            Route::post('/table/get', [EmailController::class, 'ajaxTableGetQuery'])
                ->name('dashboard.email.ajax.table.get');

            ## Acciones sobre datos de la tabla [update, create...]
            Route::match(['put', 'patch', 'post'], '/table/action', [EmailController::class, 'ajaxTableActions'])
                ->name('dashboard.email.ajax.table.actions');
        });

    });

############################################################
##                      Energía                           ##
############################################################
Route::group(['prefix' => '/energy', 'middleware' => ['auth', 'verified']],
    function () {

        Route::get('/index', [HardwareEnergyController::class, 'index'])
            ->name('dashboard.energy.index');

        Route::get('/create', [HardwareEnergyController::class, 'create'])
            ->name('dashboard.energy.create');

        Route::post('/store', [HardwareEnergyController::class, 'store'])
            ->name('dashboard.energy.store');

        Route::get('/{model}/edit', [HardwareEnergyController::class, 'edit'])
            ->name('dashboard.energy.edit');

        Route::match(['post', 'put', 'patch'], '/update/{model?}', [HardwareEnergyController::class, 'update'])
            ->name('dashboard.energy.update');

        Route::match(['POST', 'DELETE'], '/destroy/{model?}', [HardwareEnergyController::class, 'destroy'])
            ->name('dashboard.energy.destroy');
    });

############################################################
##                    Plataformas                         ##
############################################################
Route::group(['prefix' => '/platform', 'middleware' => ['auth', 'verified']],
    function () {
        Route::get('/index', [PlatformController::class, 'index'])
            ->name('dashboard.platform.index');
        Route::get('/create', [PlatformController::class, 'create'])
            ->name('dashboard.platform.create');
        Route::post('/store', [PlatformController::class, 'store'])
            ->name('dashboard.platform.store');
        Route::get('/{model}/edit', [PlatformController::class, 'edit'])
            ->name('dashboard.platform.edit');
        Route::match(['post', 'put', 'patch'], '/update/{model?}', [PlatformController::class, 'update'])
            ->name('dashboard.platform.update');
        Route::match(['POST', 'DELETE'], '/destroy/{model?}', [PlatformController::class, 'destroy'])
            ->name('dashboard.platform.destroy');

        Route::group(['prefix' => '/ajax'], function () {
            Route::post('/table/get', [PlatformController::class, 'ajaxTableGetQuery'])
                ->name('dashboard.platform.ajax.table.get');

            ## Acciones sobre datos de la tabla [update, create...]
            Route::match(['put', 'patch', 'post'], '/table/action', [PlatformController::class, 'ajaxTableActions'])
                ->name('dashboard.platform.ajax.table.actions');
        });
    });

############################################################
##                     Etiquetas                          ##
############################################################
Route::group(['prefix' => '/tag', 'middleware' => ['auth', 'verified']],
    function () {
        Route::get('/index', [TagController::class, 'index'])
            ->name('dashboard.tag.index');
        Route::get('/create', [TagController::class, 'create'])
            ->name('dashboard.tag.create');
        Route::post('/store', [TagController::class, 'store'])
            ->name('dashboard.tag.store');
        Route::get('/{tag}/edit', [TagController::class, 'edit'])
            ->name('dashboard.tag.edit');
        Route::match(['post', 'put', 'patch'], '/update/{tag?}', [TagController::class, 'update'])
            ->name('dashboard.tag.update');
        Route::match(['POST', 'DELETE'], '/destroy/{tag?}', [TagController::class, 'destroy'])
            ->name('dashboard.tag.destroy');

        Route::group(['prefix' => '/ajax'], function () {

            /*
            Route::get('/get/all', [TagController::class, 'ajaxGetTags'])
                ->name('dashboard.tag.ajax.get.all');
            */

            Route::post('/table/get', [TagController::class, 'ajaxTableGetQuery'])
                ->name('dashboard.tag.ajax.table.get');

            ## Acciones sobre datos de la tabla [update, create...]
            Route::match(['put', 'patch', 'post'], '/table/action', [TagController::class, 'ajaxTableActions'])
                ->name('dashboard.tag.ajax.table.actions');
        });
    });

############################################################
##                     Categorías                         ##
############################################################
Route::group(['prefix' => '/category', 'middleware' => ['auth', 'verified']],
    function () {
        Route::get('/index', [CategoryController::class, 'index'])
            ->name('dashboard.category.index');
        Route::get('/create', [CategoryController::class, 'create'])
            ->name('dashboard.category.create');
        Route::post('/store', [CategoryController::class, 'store'])
            ->name('dashboard.category.store');
        Route::get('/{model}/edit', [CategoryController::class, 'edit'])
            ->name('dashboard.category.edit');
        Route::match(['post', 'put', 'patch'], '/update/{category?}', [CategoryController::class, 'update'])
            ->name('dashboard.category.update');
        Route::match(['POST', 'DELETE'], '/destroy/{category?}', [CategoryController::class, 'destroy'])
            ->name('dashboard.category.destroy');

        Route::group(['prefix' => '/ajax'], function () {

            /*
            Route::get('/get/all', [TagController::class, 'ajaxGetTags'])
                ->name('dashboard.tag.ajax.get.all');
            */

            Route::get('/html/get/{category}/subcategories/{content?}', [CategoryController::class, 'ajaxGetHtmlSubcategories'])
                ->name('dashboard.category.ajax.html.subcategories');

            Route::post('/table/get', [CategoryController::class, 'ajaxTableGetQuery'])
                ->name('dashboard.category.ajax.table.get');

            ## Acciones sobre datos de la tabla [update, create...]
            Route::match(['put', 'patch', 'post'], '/table/action', [CategoryController::class, 'ajaxTableActions'])
                ->name('dashboard.category.ajax.table.actions');
        });
    });

############################################################
##                     Tecnologías                        ##
############################################################

routes/web.php
<?php

use App\Http\Controllers\FileController;
use App\Http\Controllers\FileThumbnailController;
use App\Http\Controllers\LanguageController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
})->name('home');

## Documentación
Route::middleware(['auth:sanctum', 'verified'])->get('/docs', function () {
    return view('documentation');
})->name('documentation');

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix' => '/languages'], function () {
    Route::group(['prefix' => '/ajax'], function () {
        Route::match(['get', 'post'], '/get/languages', [LanguageController::class, 'ajaxGetLanguages'])
            ->name('language.ajax.get.languages');
    });
});

Route::group(['prefix' => '/file'], function () {

    Route::group(['prefix' => '/thumbnail'], function () {
        Route::get('/get/{module}/{id}/{slug?}', [FileThumbnailController::class, 'get'])
            ->name('file.thumbnail.get');
    });


    Route::get('/get/{module}/{id}/{slug?}', [FileController::class, 'get'])
        ->name('file.get');

    Route::post('/upload', [FileController::class, 'upload'])
        ->name('file.upload');

    Route::get('/download/{module}/{id}/{slug?}', [FileController::class, 'download'])
        ->name('file.download');

    Route::get('/resize/{module}/{id}/{width}/{slug?}', [FileController::class, 'resizeAndGet'])
        ->name('file.resize');

    Route::post('/delete/{id}', [FileController::class, 'delete'])
        ->name('file.delete');

});

Auth::routes();


/**
 * Ruta por defecto cuando no se encuentra una petición.
 */
Route::fallback(function () {
    return abort(404); //default 404
});

app/Models/FileThumbnail.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use function route;
use function storage_path;

/**
 * Class FileThumbnail
 */
class FileThumbnail extends Model
{
    protected $table = 'file_thumbnails';
    protected $guarded = [
        'id'
    ];

    public static $genericImages = [
        'error' => 'error.png',
        'default' => 'default.png',
        'not_found' => 'not_found.png',
        'not_image' => 'not_image.png',  // No Es una imagen
        'not_authorized' => 'not_authorized.png',
        'not_allowed' => 'not_allowed.png',
        'not_allowed_extension' => 'not_allowed_extension.png',
        'not_allowed_size' => 'not_allowed_size.png',
        'not_allowed_type' => 'not_allowed_type.png',
        'not_available' => 'not_available.png',
    ];

    /**
     * Devuelve la ruta hacia la imagen.
     *
     * @return string
     */
    public function getUrlAttribute()
    {

        if ($this->path && $this->name && !$this->deleted_at) {
            return route('file.thumbnail.get', [
                'module' => $this->module,
                'id' => $this->id,
                'slug' => $this->name,
            ]);
        }

        return FileThumbnail::$genericImages['not_found'];
    }

    /**
     * Devuelve la ruta hacia la imagen dentro del sistema de archivos.
     *
     * @return string
     */
    public function getStoragePathFileAttribute()
    {
        if ($this->storage_path) {
            return storage_path('app/' . $this->storage_path . '/' . $this->name);
        }

        return '';
    }
}

app/Http/Controllers/Api/User/V1/UserController.php
<?php

namespace App\Http\Controllers\Api\User\V1;

use App\Http\Controllers\Controller;
use App\Http\Requests\Api\User\CreateRequest;
use App\Http\Requests\Api\User\DeleteRequest;
use App\Http\Requests\Api\User\IndexRequest;
use App\Http\Requests\Api\User\ShowRequest;
use App\Http\Resources\UserResource;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use JsonHelper;

/**
 * Class UserController
 * @package App\Http\Controllers\Api\User
 */
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param \App\Http\Requests\Api\User\IndexRequest $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function index(IndexRequest $request)
    {
        //TODO → Implementar paginación

        //$users = User::all(['id', 'name', 'surname', 'created_at']);
        $users = UserResource::collection(User::all());

        return JsonHelper::success(['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param \App\Http\Requests\Api\User\CreateRequest $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function create(CreateRequest $request)
    {
        ## Bloqueo registro de usuarios hasta tener roles definidos en toda la aplicación
        return JsonHelper::forbidden();

        $data = $request->validated();
        $data['password'] = Hash::make($data['password']);

        $user = User::create($data);

        //$newToken = $user->createToken('login');

        // TODO → Enviar email de confirmación al usuario

        return JsonHelper::created([
            'message' => 'User created successfully',
            'user' => $user,
            //'password' => $request->password,
            //'token' => $newToken->plainTextToken,
        ]);
    }

    /**
     * Devuelve los datos de un usuario.
     *
     * @param \App\Http\Requests\Api\User\ShowRequest $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function show(ShowRequest $request)
    {
        $user = User::findOrFail($request->user_id);

        return JsonHelper::success(['user' => new UserResource($user)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(Request $request)
    {
        $user = User::findOrFail($request->user_id);

        $user = $user->updateModel($request);

        return JsonHelper::updated(['user' => new UserResource($user)]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Http\Requests\Api\User\DeleteRequest $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy(DeleteRequest $request)
    {
        $user = User::findOrFail($request->user_id);

        if ($user->safeDelete()) {
            return JsonHelper::deleted(['message' => 'User deleted successfully']);
        }

        return JsonHelper::failed('User could not be deleted');
    }
}

resources/views/dashboard/users/layouts/_content_details.blade.php
<div role="tabpanel"
     class="tab-pane fade"
     id="details">

    <div class="row">
        <div class="col-md-6">
            <label>Profesión</label>
        </div>
        <div class="col-md-6">
            <p>
                {{ $user->details->profession }}
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <label>Web</label>
        </div>
        <div class="col-md-6">
            <a href="{{ $user->details->web }}"
               title="Web de {{ $user->name }}">
                {{ $user->details->web }}
            </a>
        </div>
    </div>
</div>

resources/views/dashboard/users/layouts/_content_profile.blade.php
<div role="tabpanel"
     class="tab-pane fade show active"
     id="profile">

    @if(RoleHelper::isAdmin())
        <div class="row">
            <div class="col-md-2">
                <label>
                    ID
                </label>
            </div>

            <div class="col-md-6">
                <p>
                    {{ $user->id }}
                </p>
            </div>
        </div>
    @endif

    <div class="row">
        <div class="col-md-2">
            <label>
                Teléfono
            </label>
        </div>

        <div class="col-md-6">
            <p>
                {{ $user->data->phone }}
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            <label>
                Descripción
            </label>
        </div>

        <div class="col-md-6">
            <p>
                {{ $user->data->description }}
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            <label>
                Biografía
            </label>
        </div>

        <div class="col-md-6">
            <p>
                {{ $user->data->bio }}
            </p>
        </div>
    </div>

</div>

resources/views/dashboard/users/layouts/_content_social.blade.php
<div role="tabpanel"
     class="tab-pane fade"
     id="social">

    <div class="row mt-4 mb-4 text-center font-weight-bold">
        <div class="col-md-3">
            Red Social
        </div>

        <div class="col-md-3">
            User
        </div>

        <div class="col-md-6">
            Link
        </div>
    </div>

    @foreach($user->socials as $social)
        <div class="row text-center">
            <div class="col-md-3 text-left">
                <i class="{{ $social->icon }} font-weight-bold"
                   style="color: {{ $social->color }}" ></i>
                <label>
                    {{ $social->name }}
                </label>
            </div>

            <div class="col-md-3">
                <a href="{{ $social->url }}"
                   title="{{ $social->name }} - {{ $social->nick }}">
                    {{ $social->nick }}
                </a>
            </div>

            <div class="col-md-6">
                <a href="{{ $social->url }}"
                   title="{{ $social->name }} - {{ $social->nick }}">
                    {{ $social->url }}
                </a>
            </div>
        </div>
    @endforeach
</div>

resources/views/dashboard/users/layouts/_sidebar_left.blade.php
<div class="col-12 col-md-3 user-profil-part pull-left">
    {{-- User Card --}}
    <div class="row ">
        @if(RoleHelper::canUserEdit($user->id))

            TODO: PONER CROPPER NUEVO
            {{--
            <v-cropper-image style="margin: -90px auto 0 auto;"
                    width="500"
                    preview_width="150"
                    api_id="{{ $user->id }}"
                    name="{{ $user->name }}"
                    api_url="{{ route('panel.ajax.user.avatar.upload') }}"
                    csrf_token="{{csrf_token()}}"
                    image_path="{{$user->urlAvatar}}"></v-cropper-image>
            --}}
        @else
            <div class="col-12 user-image text-center">
                <img class="rounded-circle"
                     src="{{ $user->urlAvatar }}"
                     title="Imagen de {{ $user->name }}"
                     alt="Imagen de {{ $user->name }}" />
            </div>
        @endif

        <div class="col-12 user-detail-section1 text-center">
            <button class="btn btn-warning btn-block follow">
                <i class="fas fa-file-download"></i>
                Descargar Curriculum
            </button>

            <button class="btn btn-danger btn-block">
                <i class="fas fa-user-shield"></i>
                Reportar Usuario
            </button>

            <button class="btn btn-dark btn-block">
                <i class="fas fa-envelope-open"></i>
                Enviar Mensaje
            </button>

            {{--
            <a href="{{route('dashboard.users.add', ['user_id' => $user->id])}}"
               class="btn btn-primary btn-block">
                <i class="fas fa-user-edit"></i>
                Editar Perfil
            </a>

            <a href="{{route('dashboard.users.add')}}"
               class="btn btn-danger btn-block">
                <i class="fas fa-trash"></i>
                Eliminar Cuenta
            </a>
            --}}
        </div>

        {{-- Seguidores --}}
        <div class="row user-detail-row">
            <div class="col-12 user-detail-section2 pull-left">
                <div class="border"></div>
                <p>FOLLOWER</p>
                <span>320</span>
            </div>
        </div>
    </div>
</div>

resources/views/dashboard/users/layouts/_sidebar_right.blade.php
<div class="col-md-4 img-main-rightPart">
    {{-- Sección 1 --}}
    <div class="row mt-5 mb-5">
        <div class="col-md-12">
            <h6 class="text-center">
                Section Right 1
            </h6>
        </div>

        <div class="col-md-12 text-center">
            <a href="#">
                <img src="{{ asset('images/icons/programming-languages/laravel.png') }}">
            </a>
        </div>
    </div>

    {{-- Sección 2 --}}
    <div class="row mt-5 mb-5">
        <div class="col-md-12">
            <h6 class="text-center">
                Section Right 2
            </h6>
        </div>

        <div class="col-md-12 text-center">
            <a href="#">
                <img src="{{ asset('images/icons/programming-languages/vue.png') }}">
            </a>
        </div>
    </div>
</div>